name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
    
  MY_GITHUB:
    description: "Github event"
    required: false
    default: "not provided"

# runs:
#   using: "docker"
#   image: "Dockerfile"

runs:
  using: "composite"
  steps:
    - name: tests
      shell: bash
      run: |
         pwd
         tree
         
branding:
  icon: "mic"
  color: "purple"

