name: Call me

on: 
  workflow_dispatch:
  
permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2
     
      # Run the action. Note: could also be a binary, etc
      - uses: ./
        with:
          my-name: "lolo"
