name: A workflow with injection vuln
on: push
jobs:
  injection-ok1:
    name: Injection1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: ${{ github.event.commits[0].message }}
      # https://gist.github.com/ovitente/36e6d85304e8627b6f86160352257b0e
      - env : { EVENT : "${{ toJson(github.event) }}" }
        run : "echo EVENT=$EVENT"
  injection-ok2:
    name: Injection2
    runs-on: ubuntu-latest
    steps:
        - name: step1
          shell: bash
          env: 
            MYINPUT: ${{ github.event.commits[0].message }}
          run: |
              echo MYINPUT: $MYINPUT
  injection-success:
    name: Injection3
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
              echo "title is ${{ github.event.commits[0].message }}"


